; --------------------------------------------------------------------------------
; Sprite mappings - output from SonMapEd - Sonic 1 format
; --------------------------------------------------------------------------------

Map_SSonic:
                dc.w MSS_1B4-Map_SSonic
		dc.w MSS_1C9-Map_SSonic
                dc.w MSS_1E3-Map_SSonic
		dc.w MSS_1FD-Map_SSonic
                dc.w MSS_217-Map_SSonic
		dc.w MSS_236-Map_SSonic
                dc.w MSS_255-Map_SSonic
		dc.w MSS_26F-Map_SSonic
                dc.w MSS_289-Map_SSonic
		dc.w MSS_299-Map_SSonic
                dc.w MSS_2A9-Map_SSonic
		dc.w MSS_2B9-Map_SSonic
                dc.w MSS_2C4-Map_SSonic
		dc.w MSS_2D4-Map_SSonic
                dc.w MSS_2E4-Map_SSonic
		dc.w MSS_2F4-Map_SSonic
                dc.w MSS_2FF-Map_SSonic
		dc.w MSS_314-Map_SSonic
                dc.w MSS_32E-Map_SSonic
		dc.w MSS_343-Map_SSonic
                dc.w MSS_358-Map_SSonic
		dc.w MSS_36D-Map_SSonic
                dc.w MSS_387-Map_SSonic
		dc.w MSS_39C-Map_SSonic
                dc.w MSS_3B1-Map_SSonic
		dc.w MSS_3C1-Map_SSonic
                dc.w MSS_3D6-Map_SSonic
		dc.w MSS_3E6-Map_SSonic
                dc.w MSS_3F1-Map_SSonic
		dc.w MSS_401-Map_SSonic
                dc.w MSS_416-Map_SSonic
		dc.w MSS_426-Map_SSonic
                dc.w MSS_431-Map_SSonic
		dc.w MSS_44B-Map_SSonic
                dc.w MSS_46A-Map_SSonic
		dc.w MSS_484-Map_SSonic
                dc.w MSS_49E-Map_SSonic
		dc.w MSS_4BD-Map_SSonic
                dc.w MSS_4DC-Map_SSonic
		dc.w MSS_4F6-Map_SSonic
                dc.w MSS_515-Map_SSonic
		dc.w MSS_525-Map_SSonic
                dc.w MSS_535-Map_SSonic
		dc.w MSS_545-Map_SSonic
                dc.w MSS_550-Map_SSonic
		dc.w MSS_560-Map_SSonic
                dc.w MSS_570-Map_SSonic
		dc.w MSS_580-Map_SSonic
                dc.w MSS_58B-Map_SSonic
		dc.w MSS_5A0-Map_SSonic
                dc.w MSS_5BA-Map_SSonic
		dc.w MSS_5D4-Map_SSonic
                dc.w MSS_5E9-Map_SSonic
		dc.w MSS_5FE-Map_SSonic
                dc.w MSS_618-Map_SSonic
		dc.w MSS_632-Map_SSonic
                dc.w MSS_64C-Map_SSonic
		dc.w MSS_661-Map_SSonic
                dc.w MSS_676-Map_SSonic
		dc.w MSS_68B-Map_SSonic
                dc.w MSS_6A5-Map_SSonic
		dc.w MSS_6BA-Map_SSonic
                dc.w MSS_6CF-Map_SSonic
		dc.w MSS_6E4-Map_SSonic
                dc.w MSS_6FE-Map_SSonic
		dc.w MSS_713-Map_SSonic
                dc.w MSS_728-Map_SSonic
		dc.w MSS_73D-Map_SSonic
                dc.w MSS_752-Map_SSonic
		dc.w MSS_75D-Map_SSonic
                dc.w MSS_76D-Map_SSonic
		dc.w MSS_77D-Map_SSonic
                dc.w MSS_78D-Map_SSonic
		dc.w MSS_79D-Map_SSonic
                dc.w MSS_7AD-Map_SSonic

