; Sprite mappings - generated by Flex - Sonic 1 format

Map_Edge:
	dc.w DEW_Frame0-Map_Edge, YSY_Frame1-Map_Edge
	dc.w IRY_Frame2-Map_Edge, JVZ_Frame3-Map_Edge
	dc.w DJS_Frame4-Map_Edge, CKR_Frame5-Map_Edge
	dc.w AGP_Frame6-Map_Edge, QIR_Frame7-Map_Edge
	dc.w UXQ_Frame8-Map_Edge, WCB_Frame9-Map_Edge
	dc.w TDH_FrameA-Map_Edge, NWI_FrameB-Map_Edge
	dc.w PHV_FrameC-Map_Edge, LUB_FrameD-Map_Edge


DEW_Frame0: dc.b  $7
	dc.b  $E0, $5, $8, $AA, $F8
	dc.b  $F0, $1, $8, $41, $F8
	dc.b  $F0, $1, $0, $21, $0
	dc.b  $0, $1, $8, $41, $F8
	dc.b  $0, $1, $8, $1F, $0
	dc.b  $10, $1, $8, $41, $F8
	dc.b  $10, $1, $0, $21, $0
YSY_Frame1: dc.b  $8
	dc.b  $F0, $1, $8, $41, $F8
	dc.b  $F0, $1, $0, $21, $0
	dc.b  $0, $1, $8, $41, $F8
	dc.b  $0, $1, $8, $1F, $0
	dc.b  $10, $1, $8, $41, $F8
	dc.b  $10, $1, $0, $21, $0
	dc.b  $E0, $1, $8, $41, $F8
	dc.b  $E0, $1, $8, $1F, $0
IRY_Frame2: dc.b  $8
	dc.b  $E8, $0, $0, $22, $0
	dc.b  $E0, $5, $8, $AA, $F8
	dc.b  $F0, $1, $8, $41, $F8
	dc.b  $0, $1, $8, $41, $F8
	dc.b  $10, $1, $8, $41, $F8
	dc.b  $F0, $1, $8, $1F, $0
	dc.b  $0, $1, $0, $21, $0
	dc.b  $10, $1, $8, $1F, $0
JVZ_Frame3: dc.b  $8
	dc.b  $F0, $1, $8, $41, $F8
	dc.b  $0, $1, $8, $41, $F8
	dc.b  $10, $1, $8, $41, $F8
	dc.b  $F0, $1, $8, $1F, $0
	dc.b  $0, $1, $0, $21, $0
	dc.b  $10, $1, $8, $1F, $0
	dc.b  $E0, $1, $8, $41, $F8
	dc.b  $E0, $1, $0, $21, $0
DJS_Frame4: dc.b  $7
	dc.b  $E0, $5, $8, $AA, $F8
	dc.b  $F0, $1, $8, $41, $F8
	dc.b  $0, $1, $8, $41, $F8
	dc.b  $10, $1, $8, $41, $F8
	dc.b  $F0, $1, $8, $1F, $0
	dc.b  $0, $1, $8, $1F, $0
	dc.b  $10, $1, $8, $1F, $0
CKR_Frame5: dc.b  $8
	dc.b  $E8, $0, $0, $22, $0
	dc.b  $E0, $5, $8, $AA, $F8
	dc.b  $F0, $1, $8, $41, $F8
	dc.b  $0, $1, $8, $41, $F8
	dc.b  $10, $1, $8, $41, $F8
	dc.b  $F0, $1, $0, $21, $0
	dc.b  $0, $1, $0, $21, $0
	dc.b  $10, $1, $0, $21, $0
AGP_Frame6: dc.b  $1
	dc.b  $E0, $1, $0, $4C, $FC
QIR_Frame7: dc.b  $1
	dc.b  $C0, $1, $1, $2B, $FC
UXQ_Frame8: dc.b  $1
	dc.b  $C0, $1, $1, $2D, $FC
WCB_Frame9: dc.b  $1
	dc.b  $C0, $3, $1, $2B, $FC
TDH_FrameA: dc.b  $2
	dc.b  $C0, $3, $1, $2B, $FC
	dc.b  $E0, $3, $1, $2B, $FC
NWI_FrameB: dc.b  $3
	dc.b  $C0, $3, $1, $2B, $FC
	dc.b  $E0, $3, $1, $2B, $FC
	dc.b  $0, $3, $1, $2B, $FC
PHV_FrameC: dc.b  $4
	dc.b  $C0, $3, $1, $2B, $FC
	dc.b  $E0, $3, $1, $2B, $FC
	dc.b  $0, $3, $1, $2B, $FC
	dc.b  $20, $3, $1, $2B, $FC
LUB_FrameD: dc.b  $1
	dc.b  $F8, $5, $0, $1, $F8
