; Sprite mappings - generated by Flex - Sonic 1 format

M64609712:
	dc.w 0, ZKC_Frame1-M64609712
	dc.w VDX_Frame2-M64609712, QTC_Frame3-M64609712
	dc.w LBI_Frame4-M64609712, FJQ_Frame5-M64609712
	dc.w HIU_Frame6-M64609712, HTM_Frame7-M64609712
	dc.w IGH_Frame8-M64609712

ZKC_Frame1: dc.b  $1
	dc.b  $F4, $A, $0, $0, $F4
VDX_Frame2: dc.b  $1
	dc.b  $F0, $F, $0, $9, $F0
QTC_Frame3: dc.b  $1
	dc.b  $F0, $F, $0, $19, $F0
LBI_Frame4: dc.b  $1
	dc.b  $F0, $F, $0, $29, $F0
FJQ_Frame5: dc.b  $1
	dc.b  $F0, $F, $0, $39, $F0
HIU_Frame6: dc.b  $1
	dc.b  $F0, $F, $0, $49, $F0
HTM_Frame7: dc.b  $1
	dc.b  $F2, $F, $0, $59, $F0
IGH_Frame8: dc.b  $1
	dc.b  $F4, $A, $0, $69, $F2
