; Sprite mappings - generated by Flex - Sonic 1 format

Map_Island:
	dc.w OIC_Frame0-Map_Island, FUN_Frame1-Map_Island


OIC_Frame0: dc.b  $2
	dc.b  $F0, $D, $0, $3, $E0
	dc.b  $F0, $D, $0, $B, $0
FUN_Frame1: dc.b  $1
	dc.b  $F8, $8, $0, $0, $F4
