; Sprite mappings - generated by Flex - Sonic 1 format

Map_Monitor:
	dc.w DBT_Frame0-Map_Monitor, HTZ_Frame1-Map_Monitor
	dc.w RKY_Frame2-Map_Monitor, IAT_Frame3-Map_Monitor
	dc.w TQZ_Frame4-Map_Monitor, XNI_Frame5-Map_Monitor
	dc.w TLU_Frame6-Map_Monitor, WLD_Frame7-Map_Monitor
	dc.w MBC_Frame8-Map_Monitor, MEQ_Frame9-Map_Monitor
	dc.w ZQO_FrameA-Map_Monitor, XQR_FrameB-Map_Monitor


DBT_Frame0: dc.b  $1
	dc.b  $F0, $F, $0, $0, $F0
HTZ_Frame1: dc.b  $2
	dc.b  $F6, $5, $0, $10, $F8
	dc.b  $F0, $F, $0, $0, $F0
RKY_Frame2: dc.b  $2
	dc.b  $F6, $5, $0, $14, $F8
	dc.b  $F0, $F, $0, $0, $F0
IAT_Frame3: dc.b  $2
	dc.b  $F6, $5, $0, $18, $F8
	dc.b  $F0, $F, $0, $0, $F0
TQZ_Frame4: dc.b  $2
	dc.b  $F6, $5, $0, $1C, $F8
	dc.b  $F0, $F, $0, $0, $F0
XNI_Frame5: dc.b  $2
	dc.b  $F6, $5, $0, $24, $F8
	dc.b  $F0, $F, $0, $0, $F0
TLU_Frame6: dc.b  $2
	dc.b  $F6, $5, $0, $28, $F8
	dc.b  $F0, $F, $0, $0, $F0
WLD_Frame7: dc.b  $2
	dc.b  $F6, $5, $0, $2C, $F8
	dc.b  $F0, $F, $0, $0, $F0
MBC_Frame8: dc.b  $2
	dc.b  $F6, $5, $0, $30, $F8
	dc.b  $F0, $F, $0, $0, $F0
MEQ_Frame9: dc.b  $2
	dc.b  $F6, $5, $0, $34, $F8
	dc.b  $F0, $F, $0, $0, $F0
ZQO_FrameA: dc.b  $2
	dc.b  $F6, $5, $0, $20, $F8
	dc.b  $F0, $F, $0, $0, $F0
XQR_FrameB: dc.b  $1
	dc.b  $0, $D, $0, $38, $F0
