; Sprite mappings - generated by Flex - Sonic 1 format

Map_PowerUpCard:
	dc.w RMF_Frame0-Map_PowerUpCard, MEX_Frame1-Map_PowerUpCard
	dc.w EDK_Frame2-Map_PowerUpCard, IAO_Frame3-Map_PowerUpCard
	dc.w WJI_Frame4-Map_PowerUpCard, MQH_Frame5-Map_PowerUpCard
	dc.w OLO_Frame6-Map_PowerUpCard, BAB_Frame7-Map_PowerUpCard
	dc.w HLI_Frame8-Map_PowerUpCard, WRQ_Frame9-Map_PowerUpCard
	dc.w XJF_FrameA-Map_PowerUpCard, CDT_FrameB-Map_PowerUpCard
	dc.w XII_FrameC-Map_PowerUpCard, YND_FrameD-Map_PowerUpCard
	dc.w BPS_FrameE-Map_PowerUpCard, ILZ_FrameF-Map_PowerUpCard
	dc.w YHK_Frame10-Map_PowerUpCard, PLE_Frame11-Map_PowerUpCard
	dc.w TKI_Frame12-Map_PowerUpCard, GHT_Frame13-Map_PowerUpCard
	dc.w IUF_Frame14-Map_PowerUpCard, IXU_Frame15-Map_PowerUpCard
	dc.w SFD_Frame16-Map_PowerUpCard, ORB_Frame17-Map_PowerUpCard
	dc.w KUC_Frame18-Map_PowerUpCard, XCP_Frame19-Map_PowerUpCard
	dc.w CUR_Frame1A-Map_PowerUpCard, HXT_Frame1B-Map_PowerUpCard
	dc.w SQJ_Frame1C-Map_PowerUpCard, GOZ_Frame1D-Map_PowerUpCard
	dc.w SLE_Frame1E-Map_PowerUpCard, JZJ_Frame1F-Map_PowerUpCard
	dc.w JKM_Frame20-Map_PowerUpCard, CGG_Frame21-Map_PowerUpCard
	dc.w SJT_Frame22-Map_PowerUpCard

RMF_Frame0: dc.b  $8
	dc.b  $F8, $5, $0, $3D, $B2
	dc.b  $F8, $5, $0, $2F, $C0
	dc.b  $F8, $5, $0, $2B, $D0
	dc.b  $F8, $1, $0, $1D, $DF
	dc.b  $F8, $5, $0, $8, $E7
	dc.b  $F8, $5, $0, $15, $0
	dc.b  $F8, $5, $0, $2F, $10
	dc.b  $F8, $5, $0, $41, $20
MEX_Frame1: dc.b  $8
	dc.b  $F8, $5, $0, $3D, $DA
	dc.b  $F8, $5, $0, $33, $E8
	dc.b  $F8, $1, $0, $1D, $F7
	dc.b  $F8, $5, $0, $2B, $FF
	dc.b  $F8, $5, $0, $C, $E
	dc.b  $F8, $5, $0, $0, $1E
	dc.b  $F8, $5, $0, $3D, $2D
	dc.b  $F8, $5, $0, $19, $3B
EDK_Frame2: dc.b  $D
	dc.b  $F8, $5, $0, $C, $B0
	dc.b  $F8, $5, $0, $2F, $C0
	dc.b  $F8, $5, $0, $45, $D0
	dc.b  $F8, $5, $0, $4, $DF
	dc.b  $F8, $0, $0, $1D, $EE
	dc.b  $0, $4, $0, $25, $EE
	dc.b  $F8, $1, $0, $4, $FA
	dc.b  $F8, $1, $0, $10, $2
	dc.b  $F8, $0, $0, $1D, $14
	dc.b  $0, $4, $0, $1F, $10
	dc.b  $F8, $5, $0, $45, $1C
	dc.b  $F8, $5, $0, $27, $2B
	dc.b  $F8, $5, $0, $33, $3B
IAO_Frame3: dc.b  $9
	dc.b  $F8, $0, $0, $1D, $CE
	dc.b  $0, $4, $0, $1F, $CA
	dc.b  $F8, $5, $0, $45, $D6
	dc.b  $F8, $5, $0, $27, $E5
	dc.b  $F8, $5, $0, $33, $F5
	dc.b  $F8, $5, $0, $C, $E
	dc.b  $F8, $5, $0, $0, $1E
	dc.b  $F8, $5, $0, $3D, $2D
	dc.b  $F8, $5, $0, $19, $3B
WJI_Frame4: dc.b  $C
	dc.b  $F8, $5, $0, $19, $96
	dc.b  $F8, $5, $0, $2F, $A5
	dc.b  $F8, $5, $0, $27, $B5
	dc.b  $F8, $1, $0, $1D, $C5
	dc.b  $F8, $5, $0, $2B, $CD
	dc.b  $F8, $5, $0, $15, $DC
	dc.b  $F8, $5, $0, $0, $F5
	dc.b  $F8, $5, $0, $41, $3
	dc.b  $F8, $5, $0, $41, $11
	dc.b  $F8, $5, $0, $0, $1E
	dc.b  $F8, $5, $0, $8, $2C
	dc.b  $F8, $5, $0, $21, $3B
MQH_Frame5: dc.b  $A
	dc.b  $F8, $0, $0, $1D, $C6
	dc.b  $0, $4, $0, $25, $C6
	dc.b  $F8, $1, $0, $1D, $D2
	dc.b  $F8, $5, $0, $15, $DA
	dc.b  $F8, $5, $0, $19, $EA
	dc.b  $F8, $5, $0, $41, $F9
	dc.b  $F8, $5, $0, $C, $E
	dc.b  $F8, $5, $0, $0, $1E
	dc.b  $F8, $5, $0, $3D, $2D
	dc.b  $F8, $5, $0, $19, $3B
OLO_Frame6: dc.b  $D
	dc.b  $F8, $1, $0, $1D, $BB
	dc.b  $F8, $5, $0, $2B, $C3
	dc.b  $F8, $5, $0, $3D, $D2
	dc.b  $F8, $5, $0, $41, $E0
	dc.b  $F8, $5, $0, $0, $ED
	dc.b  $F8, $5, $0, $3D, $FC
	dc.b  $F8, $5, $0, $19, $A
	dc.b  $F8, $1, $0, $1D, $19
	dc.b  $F8, $1, $0, $4, $21
	dc.b  $F8, $1, $0, $10, $29
	dc.b  $F8, $0, $0, $1D, $2F
	dc.b  $0, $4, $0, $25, $2F
	dc.b  $F8, $5, $0, $C, $3B
BAB_Frame7: dc.b  $5
	dc.b  $F8, $5, $0, $3D, $FF
	dc.b  $F8, $5, $0, $41, $D
	dc.b  $F8, $5, $0, $2F, $1B
	dc.b  $F8, $5, $0, $27, $2B
	dc.b  $F8, $5, $0, $33, $3B
HLI_Frame8: dc.b  $A
	dc.b  $F8, $5, $0, $33, $E5
	dc.b  $F8, $1, $0, $4, $F4
	dc.b  $F8, $1, $0, $10, $FC
	dc.b  $F8, $1, $0, $4, $2
	dc.b  $F8, $1, $0, $10, $A
	dc.b  $F8, $0, $0, $1D, $10
	dc.b  $0, $4, $0, $25, $10
	dc.b  $F8, $5, $0, $2F, $1C
	dc.b  $F8, $5, $0, $45, $2C
	dc.b  $F8, $5, $0, $41, $3B
WRQ_Frame9: dc.b  $2
	dc.b  $F8, $0, $0, $1D, $4
	dc.b  $0, $4, $0, $1F, $0
XJF_FrameA: dc.b  $1
	dc.b  $F8, $5, $0, $21, $0
CDT_FrameB: dc.b  $2
	dc.b  $F8, $0, $0, $1D, $0
	dc.b  $0, $4, $0, $25, $0
XII_FrameC: dc.b  $1
	dc.b  $F8, $5, $0, $27, $0
YND_FrameD: dc.b  $1
	dc.b  $F8, $5, $0, $2B, $0
BPS_FrameE: dc.b  $1
	dc.b  $F8, $5, $0, $2F, $0
ILZ_FrameF: dc.b  $1
	dc.b  $F8, $5, $0, $33, $0
YHK_Frame10: dc.b  $2
	dc.b  $F8, $1, $0, $2F, $0
	dc.b  $F8, $1, $0, $37, $8
PLE_Frame11: dc.b  $1
	dc.b  $F8, $5, $0, $39, $0
TKI_Frame12: dc.b  $1
	dc.b  $F8, $5, $0, $3D, $0
GHT_Frame13: dc.b  $1
	dc.b  $F8, $5, $0, $41, $0
IUF_Frame14: dc.b  $1
	dc.b  $F8, $5, $0, $45, $0
IXU_Frame15: dc.b  $1
	dc.b  $F8, $5, $0, $49, $0
SFD_Frame16: dc.b  $1
	dc.b  $F8, $5, $0, $4D, $0
ORB_Frame17: dc.b  $1
	dc.b  $F8, $5, $0, $51, $0
KUC_Frame18: dc.b  $3
	dc.b  $F8, $0, $0, $51, $0
	dc.b  $F8, $0, $0, $53, $8
	dc.b  $0, $4, $0, $55, $0
XCP_Frame19: dc.b  $1
	dc.b  $F8, $5, $0, $57, $0
CUR_Frame1A: dc.b  $3
	dc.b  $E8, $F, $0, $5B, $0
	dc.b  $E8, $F, $0, $6B, $20
	dc.b  $10, $4, $0, $7B, $10
HXT_Frame1B: dc.b  $20
	dc.b  $F8, $0, $0, $62, $A0
	dc.b  $F8, $0, $0, $69, $A8
	dc.b  $F8, $0, $0, $66, $B0
	dc.b  $F8, $0, $0, $5E, $B8
	dc.b  $F8, $0, $0, $77, $C8
	dc.b  $F8, $0, $0, $7A, $D0
	dc.b  $F8, $0, $0, $6E, $E0
	dc.b  $F8, $0, $0, $5B, $E8
	dc.b  $F8, $0, $0, $6A, $F0
	dc.b  $F8, $8, $0, $74, $0
	dc.b  $F8, $0, $0, $6E, $20
	dc.b  $F8, $0, $0, $69, $28
	dc.b  $F8, $0, $0, $5D, $38
	dc.b  $F8, $0, $0, $62, $40
	dc.b  $F8, $0, $0, $5B, $48
	dc.b  $F8, $0, $0, $6C, $50
	dc.b  $F8, $0, $0, $61, $58
	dc.b  $F8, $0, $0, $5F, $60
	dc.b  $0, $0, $0, $6C, $C0
	dc.b  $0, $0, $0, $5F, $C8
	dc.b  $0, $0, $0, $66, $D0
	dc.b  $0, $0, $0, $5F, $D8
	dc.b  $0, $0, $0, $5B, $E0
	dc.b  $0, $0, $0, $6D, $E8
	dc.b  $0, $0, $0, $5F, $F0
	dc.b  $0, $0, $0, $77, $0
	dc.b  $0, $0, $0, $6E, $10
	dc.b  $0, $0, $0, $69, $18
	dc.b  $0, $0, $0, $5E, $28
	dc.b  $0, $0, $0, $5B, $30
	dc.b  $0, $0, $0, $6D, $38
	dc.b  $0, $0, $0, $62, $40
SQJ_Frame1C: dc.b  $1E
	dc.b  $F8, $0, $0, $5B, $BE
	dc.b  $F8, $0, $0, $6D, $C6
	dc.b  $F8, $0, $0, $6D, $CE
	dc.b  $F8, $0, $0, $63, $D4
	dc.b  $F8, $0, $0, $61, $DA
	dc.b  $F8, $0, $0, $68, $E2
	dc.b  $F8, $0, $0, $6E, $F2
	dc.b  $F8, $0, $0, $69, $FA
	dc.b  $F8, $0, $0, $74, $A
	dc.b  $F8, $0, $0, $7A, $F
	dc.b  $F8, $0, $0, $75, $19
	dc.b  $F8, $0, $0, $69, $26
	dc.b  $F8, $0, $0, $6C, $2E
	dc.b  $F8, $0, $0, $76, $3C
	dc.b  $0, $0, $0, $71, $B8
	dc.b  $0, $0, $0, $63, $BF
	dc.b  $0, $0, $0, $6E, $C6
	dc.b  $0, $0, $0, $62, $CE
	dc.b  $0, $0, $0, $6E, $DE
	dc.b  $0, $0, $0, $62, $E6
	dc.b  $0, $0, $0, $5F, $EE
	dc.b  $0, $0, $0, $5F, $FE
	dc.b  $0, $0, $0, $6B, $6
	dc.b  $0, $0, $0, $6F, $E
	dc.b  $0, $0, $0, $63, $14
	dc.b  $0, $0, $0, $6A, $1B
	dc.b  $0, $0, $0, $67, $2A
	dc.b  $0, $0, $0, $5F, $32
	dc.b  $0, $0, $0, $68, $3A
	dc.b  $0, $0, $0, $6F, $42
GOZ_Frame1D: dc.b  $1E
	dc.b  $F8, $0, $0, $5B, $BE
	dc.b  $F8, $0, $0, $6D, $C6
	dc.b  $F8, $0, $0, $6D, $CE
	dc.b  $F8, $0, $0, $63, $D4
	dc.b  $F8, $0, $0, $61, $DA
	dc.b  $F8, $0, $0, $68, $E2
	dc.b  $F8, $0, $0, $6E, $F2
	dc.b  $F8, $0, $0, $69, $FA
	dc.b  $F8, $0, $0, $74, $A
	dc.b  $F8, $0, $0, $7A, $F
	dc.b  $F8, $0, $0, $75, $19
	dc.b  $F8, $0, $0, $69, $26
	dc.b  $F8, $0, $0, $6C, $2E
	dc.b  $F8, $0, $0, $76, $3C
	dc.b  $0, $0, $0, $71, $B8
	dc.b  $0, $0, $0, $63, $BF
	dc.b  $0, $0, $0, $6E, $C6
	dc.b  $0, $0, $0, $62, $CE
	dc.b  $0, $0, $0, $6E, $DE
	dc.b  $0, $0, $0, $62, $E6
	dc.b  $0, $0, $0, $5F, $EE
	dc.b  $0, $0, $0, $5F, $FE
	dc.b  $0, $0, $0, $6B, $6
	dc.b  $0, $0, $0, $6F, $E
	dc.b  $0, $0, $0, $63, $14
	dc.b  $0, $0, $0, $6A, $1B
	dc.b  $0, $0, $0, $67, $2A
	dc.b  $0, $0, $0, $5F, $32
	dc.b  $0, $0, $0, $68, $3A
	dc.b  $0, $0, $0, $6F, $42
SLE_Frame1E: dc.b  $1E
	dc.b  $F8, $0, $0, $5B, $BE
	dc.b  $F8, $0, $0, $6D, $C6
	dc.b  $F8, $0, $0, $6D, $CE
	dc.b  $F8, $0, $0, $63, $D4
	dc.b  $F8, $0, $0, $61, $DA
	dc.b  $F8, $0, $0, $68, $E2
	dc.b  $F8, $0, $0, $6E, $F2
	dc.b  $F8, $0, $0, $69, $FA
	dc.b  $F8, $0, $0, $74, $A
	dc.b  $F8, $0, $0, $7A, $F
	dc.b  $F8, $0, $0, $75, $19
	dc.b  $F8, $0, $0, $69, $26
	dc.b  $F8, $0, $0, $6C, $2E
	dc.b  $F8, $0, $0, $76, $3C
	dc.b  $0, $0, $0, $71, $B8
	dc.b  $0, $0, $0, $63, $BF
	dc.b  $0, $0, $0, $6E, $C6
	dc.b  $0, $0, $0, $62, $CE
	dc.b  $0, $0, $0, $6E, $DE
	dc.b  $0, $0, $0, $62, $E6
	dc.b  $0, $0, $0, $5F, $EE
	dc.b  $0, $0, $0, $5F, $FE
	dc.b  $0, $0, $0, $6B, $6
	dc.b  $0, $0, $0, $6F, $E
	dc.b  $0, $0, $0, $63, $14
	dc.b  $0, $0, $0, $6A, $1B
	dc.b  $0, $0, $0, $67, $2A
	dc.b  $0, $0, $0, $5F, $32
	dc.b  $0, $0, $0, $68, $3A
	dc.b  $0, $0, $0, $6F, $42
JZJ_Frame1F: dc.b  $1E
	dc.b  $F8, $0, $0, $5B, $BE
	dc.b  $F8, $0, $0, $6D, $C6
	dc.b  $F8, $0, $0, $6D, $CE
	dc.b  $F8, $0, $0, $63, $D4
	dc.b  $F8, $0, $0, $61, $DA
	dc.b  $F8, $0, $0, $68, $E2
	dc.b  $F8, $0, $0, $6E, $F2
	dc.b  $F8, $0, $0, $69, $FA
	dc.b  $F8, $0, $0, $74, $A
	dc.b  $F8, $0, $0, $7A, $F
	dc.b  $F8, $0, $0, $75, $19
	dc.b  $F8, $0, $0, $69, $26
	dc.b  $F8, $0, $0, $6C, $2E
	dc.b  $F8, $0, $0, $76, $3C
	dc.b  $0, $0, $0, $71, $B8
	dc.b  $0, $0, $0, $63, $BF
	dc.b  $0, $0, $0, $6E, $C6
	dc.b  $0, $0, $0, $62, $CE
	dc.b  $0, $0, $0, $6E, $DE
	dc.b  $0, $0, $0, $62, $E6
	dc.b  $0, $0, $0, $5F, $EE
	dc.b  $0, $0, $0, $5F, $FE
	dc.b  $0, $0, $0, $6B, $6
	dc.b  $0, $0, $0, $6F, $E
	dc.b  $0, $0, $0, $63, $14
	dc.b  $0, $0, $0, $6A, $1B
	dc.b  $0, $0, $0, $67, $2A
	dc.b  $0, $0, $0, $5F, $32
	dc.b  $0, $0, $0, $68, $3A
	dc.b  $0, $0, $0, $6F, $42
JKM_Frame20: dc.b  $1E
	dc.b  $F8, $0, $0, $5B, $BE
	dc.b  $F8, $0, $0, $6D, $C6
	dc.b  $F8, $0, $0, $6D, $CE
	dc.b  $F8, $0, $0, $63, $D4
	dc.b  $F8, $0, $0, $61, $DA
	dc.b  $F8, $0, $0, $68, $E2
	dc.b  $F8, $0, $0, $6E, $F2
	dc.b  $F8, $0, $0, $69, $FA
	dc.b  $F8, $0, $0, $74, $A
	dc.b  $F8, $0, $0, $7A, $F
	dc.b  $F8, $0, $0, $75, $19
	dc.b  $F8, $0, $0, $69, $26
	dc.b  $F8, $0, $0, $6C, $2E
	dc.b  $F8, $0, $0, $76, $3C
	dc.b  $0, $0, $0, $71, $B8
	dc.b  $0, $0, $0, $63, $BF
	dc.b  $0, $0, $0, $6E, $C6
	dc.b  $0, $0, $0, $62, $CE
	dc.b  $0, $0, $0, $6E, $DE
	dc.b  $0, $0, $0, $62, $E6
	dc.b  $0, $0, $0, $5F, $EE
	dc.b  $0, $0, $0, $5F, $FE
	dc.b  $0, $0, $0, $6B, $6
	dc.b  $0, $0, $0, $6F, $E
	dc.b  $0, $0, $0, $63, $14
	dc.b  $0, $0, $0, $6A, $1B
	dc.b  $0, $0, $0, $67, $2A
	dc.b  $0, $0, $0, $5F, $32
	dc.b  $0, $0, $0, $68, $3A
	dc.b  $0, $0, $0, $6F, $42
CGG_Frame21: dc.b  $16
	dc.b  $F8, $0, $0, $6A, $D0
	dc.b  $F8, $0, $0, $6C, $D8
	dc.b  $F8, $0, $0, $5F, $E0
	dc.b  $F8, $0, $0, $6D, $E8
	dc.b  $F8, $0, $0, $6D, $F0
	dc.b  $F8, $0, $0, $77, $0
	dc.b  $F8, $0, $0, $7C, $8
	dc.b  $F8, $8, $0, $74, $10
	dc.b  $F8, $0, $0, $63, $30
	dc.b  $F8, $0, $0, $68, $37
	dc.b  $0, $0, $0, $67, $C8
	dc.b  $0, $0, $0, $63, $CF
	dc.b  $0, $0, $0, $5E, $D6
	dc.b  $0, $0, $0, $5B, $E8
	dc.b  $0, $0, $0, $63, $EF
	dc.b  $0, $0, $0, $6C, $F6
	dc.b  $0, $0, $0, $6E, $5
	dc.b  $0, $0, $0, $69, $D
	dc.b  $0, $4, $0, $6D, $1D
	dc.b  $0, $0, $0, $69, $2D
	dc.b  $0, $0, $0, $67, $35
	dc.b  $0, $0, $0, $6A, $3D
SJT_Frame22: dc.b  $20
	dc.b  $F8, $0, $0, $62, $A0
	dc.b  $F8, $0, $0, $69, $A8
	dc.b  $F8, $0, $0, $66, $B0
	dc.b  $F8, $0, $0, $5E, $B8
	dc.b  $F8, $0, $0, $7A, $D0
	dc.b  $F8, $0, $0, $6E, $E0
	dc.b  $F8, $0, $0, $5B, $E8
	dc.b  $F8, $0, $0, $6A, $F0
	dc.b  $F8, $8, $0, $74, $0
	dc.b  $F8, $0, $0, $6E, $20
	dc.b  $F8, $0, $0, $69, $28
	dc.b  $F8, $0, $0, $5D, $38
	dc.b  $F8, $0, $0, $62, $40
	dc.b  $F8, $0, $0, $5B, $48
	dc.b  $F8, $0, $0, $6C, $50
	dc.b  $F8, $0, $0, $61, $58
	dc.b  $F8, $0, $0, $5F, $60
	dc.b  $0, $0, $0, $6C, $C0
	dc.b  $0, $0, $0, $5F, $C8
	dc.b  $0, $0, $0, $66, $D0
	dc.b  $0, $0, $0, $5F, $D8
	dc.b  $0, $0, $0, $5B, $E0
	dc.b  $0, $0, $0, $6D, $E8
	dc.b  $0, $0, $0, $5F, $F0
	dc.b  $0, $0, $0, $6E, $10
	dc.b  $0, $0, $0, $69, $18
	dc.b  $0, $0, $0, $5E, $28
	dc.b  $0, $0, $0, $5B, $30
	dc.b  $0, $0, $0, $6D, $38
	dc.b  $0, $0, $0, $62, $40
	dc.b  $F8, $0, $0, $78, $C8
	dc.b  $0, $0, $0, $78, $0
