; DPLCs - generated by Flex - Sonic 2 format

PowerUpDPLC:
	dc.w 0, CAO_Frame1-PowerUpDPLC
	dc.w VLK_Frame2-PowerUpDPLC, ZUL_Frame3-PowerUpDPLC
	dc.w RUB_Frame4-PowerUpDPLC, VGZ_Frame5-PowerUpDPLC
	dc.w QLH_Frame6-PowerUpDPLC, BNF_Frame7-PowerUpDPLC
	dc.w LBH_Frame8-PowerUpDPLC, OZA_Frame9-PowerUpDPLC
	dc.w YJB_FrameA-PowerUpDPLC, FOE_FrameB-PowerUpDPLC
	dc.w RTZ_FrameC-PowerUpDPLC, PCR_FrameD-PowerUpDPLC
	dc.w ZKD_FrameE-PowerUpDPLC, LHZ_FrameF-PowerUpDPLC
	dc.w PBS_Frame10-PowerUpDPLC

CAO_Frame1: dc.b  $0,  $1
	dc.b  $30, $0
VLK_Frame2: dc.b  $0,  $1
	dc.b  $30, $4
ZUL_Frame3: dc.b  $0,  $1
	dc.b  $30, $8
RUB_Frame4: dc.b  $0,  $1
	dc.b  $30, $C
VGZ_Frame5: dc.b  $0,  $1
	dc.b  $30, $10
QLH_Frame6: dc.b  $0,  $1
	dc.b  $30, $14
BNF_Frame7: dc.b  $0,  $1
	dc.b  $30, $18
LBH_Frame8: dc.b  $0,  $1
	dc.b  $30, $1C
OZA_Frame9: dc.b  $0,  $1
	dc.b  $30, $20
YJB_FrameA: dc.b  $0,  $1
	dc.b  $30, $24
FOE_FrameB: dc.b  $0,  $1
	dc.b  $30, $28
RTZ_FrameC: dc.b  $0,  $1
	dc.b  $30, $2C
PCR_FrameD: dc.b  $0,  $1
	dc.b  $30, $30
ZKD_FrameE: dc.b  $0,  $1
	dc.b  $30, $34
LHZ_FrameF: dc.b  $0,  $1
	dc.b  $30, $38
PBS_Frame10: dc.b  $0,  $1
	dc.b  $30, $3C
