; Sprite mappings - generated by Flex - Sonic 1 format

Map_PowerUp:
	dc.w 0, QEX_Frame1-Map_PowerUp
	dc.w GDT_Frame2-Map_PowerUp, MCT_Frame3-Map_PowerUp
	dc.w YNZ_Frame4-Map_PowerUp, PEU_Frame5-Map_PowerUp
	dc.w EKL_Frame6-Map_PowerUp, CBK_Frame7-Map_PowerUp
	dc.w BQN_Frame8-Map_PowerUp, BJC_Frame9-Map_PowerUp
	dc.w LKQ_FrameA-Map_PowerUp, HGF_FrameB-Map_PowerUp
	dc.w ODF_FrameC-Map_PowerUp, ETR_FrameD-Map_PowerUp
	dc.w BYW_FrameE-Map_PowerUp, IEQ_FrameF-Map_PowerUp
	dc.w YER_Frame10-Map_PowerUp

QEX_Frame1: dc.b  $1
	dc.b  $F8, $5, $20, $0, $F8
GDT_Frame2: dc.b  $1
	dc.b  $F8, $5, $20, $0, $F8
MCT_Frame3: dc.b  $1
	dc.b  $F8, $5, $20, $0, $F8
YNZ_Frame4: dc.b  $1
	dc.b  $F8, $5, $20, $0, $F8
PEU_Frame5: dc.b  $1
	dc.b  $F8, $5, $20, $0, $F8
EKL_Frame6: dc.b  $1
	dc.b  $F8, $5, $20, $0, $F8
CBK_Frame7: dc.b  $1
	dc.b  $F8, $5, $20, $0, $F8
BQN_Frame8: dc.b  $1
	dc.b  $F8, $5, $20, $0, $F8
BJC_Frame9: dc.b  $1
	dc.b  $F8, $5, $20, $0, $F8
LKQ_FrameA: dc.b  $1
	dc.b  $F8, $5, $20, $0, $F8
HGF_FrameB: dc.b  $1
	dc.b  $F8, $5, $20, $0, $F8
ODF_FrameC: dc.b  $1
	dc.b  $F8, $5, $20, $0, $F8
ETR_FrameD: dc.b  $1
	dc.b  $F8, $5, $20, $0, $F8
BYW_FrameE: dc.b  $1
	dc.b  $F8, $5, $20, $0, $F8
IEQ_FrameF: dc.b  $1
	dc.b  $F8, $5, $20, $0, $F8
YER_Frame10: dc.b  $1
	dc.b  $F8, $5, $20, $0, $F8
