; Sprite mappings - generated by Flex - Sonic 1 format

Map_SpeedBooster:
	dc.w PDA_Frame0-Map_SpeedBooster, VFL_Frame1-Map_SpeedBooster
	dc.w YCU_Frame2-Map_SpeedBooster

PDA_Frame0: dc.b  $2
	dc.b  $F8, $5, $0, $0, $E8
	dc.b  $F8, $5, $0, $0, $8
VFL_Frame1: dc.b  $2
	dc.b  $F8, $5, $0, $0, $E8
	dc.b  $F8, $5, $0, $0, $8
YCU_Frame2: dc.b  $0
	even