; Sprite mappings - generated by Flex - Sonic 1 format

Map_Splats:
	dc.w @stop-Map_Splats
	dc.w @down-Map_Splats
	dc.w @up-Map_Splats


@stop: dc.b  $3
	dc.b  $E8, $8, $0, $E, $F8
	dc.b  $F0, $A, $0, $3, $F8
	dc.b  $8, $4, $0, $C, $FA
@down: dc.b  $3
	dc.b  $E8, $8, $0, $0, $F8
	dc.b  $F0, $A, $0, $3, $F8
	dc.b  $8, $4, $0, $C, $FA
@up: dc.b  $3
	dc.b  $E4, $8, $0, $E, $F8
	dc.b  $EC, $A, $0, $3, $F8
	dc.b  $4, $5, $0, $11, $FA
