	; Sprite mappings - generated by Flex - Sonic 1 format

Map_Springpole:
	dc.w @Frame0-Map_Springpole, @Frame1-Map_Springpole
	dc.w @Frame2-Map_Springpole, @Frame3-Map_Springpole


@Frame0: dc.b  $2
	dc.b  $E6, $8, $0, $0, $F0
	dc.b  $E6, $4, $0, $2, $8
@Frame1: dc.b  $3
	dc.b  $EB, $0, $0, $0, $F1
	dc.b  $E6, $0, $0, $3, $10
	dc.b  $E8, $8, $0, $4, $F8
@Frame2: dc.b  $3
	dc.b  $EE, $0, $0, $0, $F4
	dc.b  $E6, $0, $0, $3, $10
	dc.b  $EA, $8, $0, $7, $F8
@Frame3: dc.b  $3
	dc.b  $E2, $0, $0, $0, $F3
	dc.b  $E6, $0, $0, $3, $10
	dc.b  $E6, $8, $0, $A, $F8
	even