; Sprite mappings - generated by Flex - Sonic 1 format

Map_Springboard:
	dc.w CPZ_Frame0-Map_Springboard, NFU_Frame1-Map_Springboard


CPZ_Frame0: dc.b  $3
	dc.b  $E8, $D, $20, $2, $F4
	dc.b  $E8, $0, $20, $A, $14
	dc.b  $F0, $4, $20, $0, $E4
NFU_Frame1: dc.b  $3
	dc.b  $F0, $0, $20, $0, $E4
	dc.b  $F0, $8, $20, $B, $EC
	dc.b  $F0, $8, $20, $E, $4
