; Sprite mappings - generated by Flex - Sonic 1 format

Map_StompBlock:
	dc.w ZDF_Frame0-Map_StompBlock, KUR_Frame1-Map_StompBlock
	dc.w UYA_Frame2-Map_StompBlock

ZDF_Frame0: dc.b  $2
	dc.b  $F0, $7, $0, $0, $F0
	dc.b  $F0, $7, $8, $0, $0
KUR_Frame1: dc.b  $1
	dc.b  $F0, $7, $0, $0, $F0
UYA_Frame2: dc.b  $1
	dc.b  $F0, $7, $8, $0, $0
