; Sprite mappings - generated by Flex - Sonic 1 format

Map_Teleporter:
	dc.w SYV_Frame0-Map_Teleporter, QGM_Frame1-Map_Teleporter
	dc.w XWO_Frame2-Map_Teleporter, BLG_Frame3-Map_Teleporter
	dc.w ZZY_Frame4-Map_Teleporter, TUA_Frame5-Map_Teleporter
	dc.w MYW_Frame6-Map_Teleporter, ZAC_Frame7-Map_Teleporter
	dc.w KPL_Frame8-Map_Teleporter, MYP_Frame9-Map_Teleporter
	dc.w CLC_FrameA-Map_Teleporter

SYV_Frame0: dc.b  $3
	dc.b  $F8, $A, $0, $9, $E8
	dc.b  $F8, $A, $88, $9, $0
	dc.b  $F0, $A, $A0, $0, $F4
QGM_Frame1: dc.b  $1
	dc.b  $E0, $1, $20, $12, $FF
XWO_Frame2: dc.b  $1
	dc.b  $D0, $3, $20, $12, $FF
BLG_Frame3: dc.b  $8
	dc.b  $60, $3, $20, $16, $0
	dc.b  $40, $3, $20, $16, $0
	dc.b  $20, $3, $20, $16, $0
	dc.b  $0, $3, $20, $16, $0
	dc.b  $E0, $3, $20, $16, $0
	dc.b  $C0, $3, $20, $16, $0
	dc.b  $A0, $3, $20, $16, $0
	dc.b  $80, $3, $20, $16, $0
ZZY_Frame4: dc.b  $8
	dc.b  $60, $3, $28, $16, $F8
	dc.b  $40, $3, $28, $16, $F8
	dc.b  $20, $3, $28, $16, $F8
	dc.b  $0, $3, $28, $16, $F8
	dc.b  $E0, $3, $28, $16, $F8
	dc.b  $C0, $3, $28, $16, $F8
	dc.b  $A0, $3, $28, $16, $F8
	dc.b  $80, $3, $28, $16, $F8
TUA_Frame5: dc.b  $8
	dc.b  $60, $7, $20, $16, $0
	dc.b  $40, $7, $20, $16, $0
	dc.b  $20, $7, $20, $16, $0
	dc.b  $0, $7, $20, $16, $0
	dc.b  $E0, $7, $20, $16, $0
	dc.b  $C0, $7, $20, $16, $0
	dc.b  $A0, $7, $20, $16, $0
	dc.b  $80, $7, $20, $16, $0
MYW_Frame6: dc.b  $8
	dc.b  $60, $7, $28, $16, $F0
	dc.b  $40, $7, $28, $16, $F0
	dc.b  $20, $7, $28, $16, $F0
	dc.b  $0, $7, $28, $16, $F0
	dc.b  $E0, $7, $28, $16, $F0
	dc.b  $C0, $7, $28, $16, $F0
	dc.b  $A0, $7, $28, $16, $F0
	dc.b  $80, $7, $28, $16, $F0
ZAC_Frame7: dc.b  $8
	dc.b  $60, $B, $20, $16, $0
	dc.b  $40, $B, $20, $16, $0
	dc.b  $20, $B, $20, $16, $0
	dc.b  $0, $B, $20, $16, $0
	dc.b  $E0, $B, $20, $16, $0
	dc.b  $C0, $B, $20, $16, $0
	dc.b  $A0, $B, $20, $16, $0
	dc.b  $80, $B, $20, $16, $0
KPL_Frame8: dc.b  $8
	dc.b  $60, $B, $28, $16, $E8
	dc.b  $40, $B, $28, $16, $E8
	dc.b  $20, $B, $28, $16, $E8
	dc.b  $0, $B, $28, $16, $E8
	dc.b  $E0, $B, $28, $16, $E8
	dc.b  $C0, $B, $28, $16, $E8
	dc.b  $A0, $B, $28, $16, $E8
	dc.b  $80, $B, $28, $16, $E8
MYP_Frame9: dc.b  $8
	dc.b  $60, $3, $20, $12, $FF
	dc.b  $40, $3, $20, $12, $FF
	dc.b  $20, $3, $20, $12, $FF
	dc.b  $0, $3, $20, $12, $FF
	dc.b  $E0, $3, $20, $12, $FF
	dc.b  $C0, $3, $20, $12, $FF
	dc.b  $A0, $3, $20, $12, $FF
	dc.b  $80, $3, $20, $12, $FF
CLC_FrameA: dc.b  $3
	dc.b  $F8, $A, $40, $9, $E8
	dc.b  $F8, $A, $48, $9, $0
	dc.b  $F0, $A, $60, $0, $F4
