; Sprite mappings - generated by Flex - Sonic 1 format

Map_Torch:
	dc.w HQL_Frame0-Map_Torch, DMV_Frame1-Map_Torch
	dc.w LSH_Frame2-Map_Torch, YNH_Frame3-Map_Torch
	dc.w OVQ_Frame4-Map_Torch, HCA_Frame5-Map_Torch
	dc.w TSJ_Frame6-Map_Torch, UWM_Frame7-Map_Torch


HQL_Frame0: dc.b  $1
	dc.b  $E8, $7, $20, $0, $F8
DMV_Frame1: dc.b  $1
	dc.b  $E8, $7, $20, $8, $F8
LSH_Frame2: dc.b  $1
	dc.b  $E8, $7, $20, $10, $F8
YNH_Frame3: dc.b  $1
	dc.b  $E8, $7, $20, $18, $F8
OVQ_Frame4: dc.b  $1
	dc.b  $E8, $7, $28, $0, $F8
HCA_Frame5: dc.b  $1
	dc.b  $E8, $7, $28, $8, $F8
TSJ_Frame6: dc.b  $1
	dc.b  $E8, $7, $28, $10, $F8
UWM_Frame7: dc.b  $1
	dc.b  $E8, $7, $28, $18, $F8
	even
